### ISSUE TITLE
Parse JSX files

### ISSUE THREAD

**Issue by swissspidy** [mck89/peast#1]
Libraries like React are very popular and programs using it are mostly written using JSX as well. It would be useful to have it supported in this library.

My personal use case would be having a tool to extract gettext calls from a JSX source file.

I figure this could be done by introducing a new `jsx` option on the `Parser` class. By default it would be `false`.

**Comment by mck89** [comment]
@swissspidy that is already on my roadmap, i will start to work on it as soon as i can.

**Comment by mck89** [comment]
Version 1.8 with JSX syntax support has been released.

Setting the `"jsx"` option to `true` will enable JSX parsing.
