### ISSUE TITLE
Problem with compact mode breaking script

### ISSUE THREAD

**Issue by tristanleboss** [mck89/peast#11]
Hello,

It seems the compact mode breaks this script:

https://www.valeur-et-capital.com/wp-content/themes/cc_ad_valeur_et_capital_theme/elementor/widget_particules/js/particles.js?ver=5.2.2

The output is not working. Replacing with the original code made it working. I will investigate.

**Comment by mck89** [comment]
It seems that the algorithm to detect when brackets are mandatory in if/else is still buggy.
This is the part where the error occurs:

```js
pJS.fn.vendors.draw = function(){

	if(pJS.particles.shape.type == 'image'){

		if(pJS.tmp.img_type == 'svg'){

			if(pJS.tmp.count_svg >= pJS.particles.number.value){
				pJS.fn.particlesDraw();
				if(!pJS.particles.move.enable) cancelRequestAnimFrame(pJS.fn.drawAnimFrame);
				else pJS.fn.drawAnimFrame = requestAnimFrame(pJS.fn.vendors.draw);
			}else{
				//console.log('still loading...');
				if(!pJS.tmp.img_error) pJS.fn.drawAnimFrame = requestAnimFrame(pJS.fn.vendors.draw);
			}

		}else{

			if(pJS.tmp.img_obj != undefined){
				pJS.fn.particlesDraw();
				if(!pJS.particles.move.enable) cancelRequestAnimFrame(pJS.fn.drawAnimFrame);
				else pJS.fn.drawAnimFrame = requestAnimFrame(pJS.fn.vendors.draw);
			}else{
				if(!pJS.tmp.img_error) pJS.fn.drawAnimFrame = requestAnimFrame(pJS.fn.vendors.draw);
			}

		}

	}else{
		pJS.fn.particlesDraw();
		if(!pJS.particles.move.enable) cancelRequestAnimFrame(pJS.fn.drawAnimFrame);
		else pJS.fn.drawAnimFrame = requestAnimFrame(pJS.fn.vendors.draw);
	}

};
```
The first and second "if" are rendered without brackets and this causes wrong parsing of "else" part.
I'm a little busy right now, but i will take a look at it as soon as possible.

**Comment by mck89** [comment]
I've just released a new version that fixes the problem. Thank you for reporting!

**Comment by tristanleboss** [comment]
Thanks ;)
