### ISSUE TITLE
Improve error handling in stringToUTF8Array

### ISSUE THREAD

**Issue by tristanleboss** [mck89/peast#12]
In file `lib\Peast\Syntax\Utils.php`, the method `stringToUTF8Array` can in some circumstances return `false`. Indeed, `preg_split` can return `false`. In such situation, your code output a lot of warnings and crashes randomly after.

It would be cool to add a check and throw an exception. You can get the error `preg_split` encountered using `preg_last_error` function.

The most common case is badly encoded UTF-8 file (`preg_last_error` returns 4); which is the situation I encountered myself : an UTF-8 file with an ISO-8859-1 characters in a comment....

```
    /**
     * Converts a string to an array of UTF-8 characters
     * 
     * @param string $str String to convert
     * 
     * @return array
     */
    static public function stringToUTF8Array($str)
    {
        return $str === "" ?
               array() :
               preg_split('//u', $str, null, PREG_SPLIT_NO_EMPTY);
    }
```

**Comment by mck89** [comment]
I've just released the new 1.9.4 version with some improvements to handle invalid utf-8 characters.
As you suggested i've added the new EncodingException type that is thrown when the source contains invalid utf-8 characters, but i've also added the new strictEncoding option that, if set to false, allows you to change this behaviour by replacing invalid characters with the one defined in the "mbstring.substitute_character" ini setting.
