### ISSUE TITLE
Compact mode bug

### ISSUE THREAD

**Issue by tristanleboss** [mck89/peast#14]
The compact mode will transform:

`"_"+ ++t+"__"`

(notice the space after the first + sign)

by the invalid syntax:

`"_"+++t+"__"`

![image](https://user-images.githubusercontent.com/1431508/68072506-ce4b5800-fd86-11e9-881c-fc60316e2fa0.png)

**Comment by mck89** [comment]
Thank you for reporting, i'm working on a new version that will contain the fix for this error.

**Comment by mck89** [comment]
I've just released a new version that includes the fix for this error.
