### ISSUE TITLE
Composer deprecation notices: Class ... does not comply with psr-0 autoloading standard.

### ISSUE THREAD

**Issue by mikeschinkel** [mck89/peast#18]
Peast is used in WP-CLI and so this was experienced when using Composer with WP-CLI.

I thought it might be helpful for the WP-CLI maintainers if I posted an issue here as well since it appears that two (2) of the four (4) notices come from Peast.

- For more details [**see this issue**](https://github.com/wp-cli/wp-cli/issues/5365).

The following screenshot illustrates:

![composer-deprecation-notices](https://user-images.githubusercontent.com/153285/76684264-d478fd00-65e0-11ea-9a87-44fadbc561ad.png)

P.S. I hope you and your loved ones are weathering the COVID-19 storm successfully. The world is rooting for Italy.

**Comment by mck89** [comment]
We are fine, thank you 😃 I've just noticed that those two files have wrong namespaces, that's must be the problem and it should be easy to fix. I will include it in the next version.

**Comment by mck89** [comment]
I haven't really found a way to test it but i think it should be fixed now. Those two test files had a wrong namespace declaration and that's the only thing that could possibly cause that error.

**Comment by mikeschinkel** [comment]
@mck89 - I ran Composer and your errors went away, so it looks like you fixed it.  Thanks!
