### ISSUE TITLE
Regular expression literal can be mis-parsed as unterminated strings

### ISSUE THREAD

**Issue by schlessera** [mck89/peast#3]
If the parsed code has regular expression literals containing quotes, these quotes are erroneously being parsed as opening or closing a string literal.

This will in turn cause the parser to throw an `Unterminated string` error once it hits the end of the line.

As an example, the WordPress Core code contains regular expression literals like this:

```js
function escapeHTML(s) {
   var n = s;
   n = n.replace(/&/g, '&amp;');
   n = n.replace(/</g, '&lt;');
   n = n.replace(/>/g, '&gt;');
   n = n.replace(/"/g, '&quot;');

   return n;
}
```

In this example, the regular expression literal `/"/g` will be parsed as opening a double-quoted string and throw an error once it hits the next line.

Related: https://github.com/wp-cli/i18n-command/issues/98

**Comment by mck89** [comment]
Thank you for reporting, i can confirm the bug, i will work on it as soon as i can.

**Comment by mck89** [comment]
The problem should be fixed now
