### ISSUE TITLE
Failure to parse and tokenize

### ISSUE THREAD

**Issue by ElectroMW** [mck89/peast#30]
Hi there,

I've come across a failure to parse what appears to be a valid JS file;
Source: https://api-platform.com/component---src-pages-index-js-7905c18163e9101ccbec.js
Command: Peast::latest($src, ['comments' => false, 'strictEncoding' => false, 'jsx' => true])->parse();

I've also come across a failure to tokenize a file that was parsed successfully;
Source: https://api-platform.com/framework-2d6b7d2e2be378715b78.js
Command: Peast::latest($node->render(new Compact))->tokenize();

Any pointers (assuming it is not a bug) would be much appreciated.

Electro

**Comment by mck89** [comment]
I can confirm both problems.

I've just solved the first one, it was a bug when parsing html open comments inside a regex, for example: `(/<!-- [\s\S] -->/)`.

I'm still checking the second one, but it's certainly a rendering bug.

**Comment by mck89** [comment]
Solved the second problem too, it was a bug when rendering LabeledStatement in Compact mode. Thank you for reporting.

**Comment by ElectroMW** [comment]
Thank you for the fix.
