### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by afragen** [mck89/peast#31]
In PHP 8.x is seems there's a parse error as the same invoking command works under PHP 7.4

```
PHP Parse error:  syntax error, unexpected fully qualified name "\Syntax\Node\Expression", expecting "," or ";" in phar:///opt/homebrew/Cellar/wp-cli/2.4.0/bin/wp/vendor/mck89/peast/lib/Peast/Syntax/Node/JSX/JSXOpeningElement.php on line 13
```

**Comment by mck89** [comment]
You are using an old version, in [this commit](https://github.com/mck89/peast/commit/21c81cc097b9eaaaee2012534ece7eee77e4198b) the PHP8 compatibility errors with namespaces were solved.
On Travis all PHP8 tests pass so that must be the problem, try to update your version please.

**Comment by afragen** [comment]
Tested with _latest_, or at least more updated version, and it works.

**Comment by premanshup** [comment]
How can I update this for WP CLI? I'm getting the same error when I run the WP CLI command.

```
λ wp i18n make-pot wp-content/themes/astra wp-content/themes/astra/languages/astra.pot
Theme stylesheet detected.
PHP Parse error:  syntax error, unexpected fully qualified name "\Syntax\Node\Expression", expecting "," or ";" in phar://C:/wp-cli/wp-cli.phar/vendor/mck89/peast/lib/Peast/Syntax/Node/JSX/JSXOpeningElement.php on line 13

Parse error: syntax error, unexpected fully qualified name "\Syntax\Node\Expression", expecting "," or ";" in phar://C:/wp-cli/wp-cli.phar/vendor/mck89/peast/lib/Peast/Syntax/Node/JSX/JSXOpeningElement.php on line 13
```

**Comment by mck89** [comment]
Try to update composer dependencies or open a issue on WP CLI, the bug is fixed here so you must have an outdated version.
