### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by exussum12** [mck89/peast#34]
hi

The licence suggests bsd-3 composer suggests MIT

could these by synced to the preferred licence

**Comment by mck89** [comment]
Actually those are 2 different licenses, i've chosen bsd3 so i don't want to change it if it's not necessary. What message are you getting from composer?

**Comment by exussum12** [comment]
https://github.com/mck89/peast/blob/master/composer.json#L4

https://github.com/mck89/peast/blob/master/LICENSE

**Comment by mck89** [comment]
Ok sorry now i see what you mean, i didn't remember there was an entry in composer.json, thank you, i've merged your pull request
