### ISSUE TITLE
Issues parsing React Fragment short syntax

### ISSUE THREAD

**Issue by swissspidy** [mck89/peast#43]
Originally reported at https://github.com/wp-cli/i18n-command/issues/280, Peast fails to parse the following JSX using the `<>`/`</>` shorthand syntax for React fragments:

```jsx
import React from 'react';

export default class Example extends React.Component {
  render() {
    return (
        <div className="example">
          <>
          </>
        </div>
    );
  }
}
```

Errror:

```
Peast\Syntax\Exception: Unexpected: >
```

Fragments are being parsed fine if they're on the outmost side though:

```jsx
export default class Example extends React.Component {
  render() {
    return (
      <>
        <div className="example">
        </div>
      </>
    );
  }
}
```

**Comment by mck89** [comment]
I'm not a React expert so i had to find some documentation when writing the JSX parser and that documentation didn't allow fragments inside elements. I tried that syntax and it works with React so i've implemented it, now it works as expected.
