### ISSUE TITLE
Failed to parse specific js code

### ISSUE THREAD

**Issue by zauan** [mck89/peast#55]
Hi there,

it seems that the following code cannot be parsed in this configuration:

```
		$peast_options = [
			'sourceType' => Peast::SOURCE_TYPE_MODULE,
			'comments'   => true,
		];
		$ast           = Peast::latest( 'const HASH_RE = /#/g;', $peast_options )->parse();
```

**Comment by mck89** [comment]
That was a bug introduced by the latest version where i've implemented the hashbang comments parsing, the sequence `/#` was parsed as a comment but then resulted in an invalid comment. I've just fixed it and published a new release. Thank you for reporting.
