### ISSUE TITLE
Question: Is it possible to query by key name?

### ISSUE THREAD

**Issue by heidkaemper** [mck89/peast#56]
First of all, thank you for this package! It is helping a lot.

I was wondering if it's possible to query not just for values but for key names as well. Something like this:

```
$ast = Peast::latest($source)->parse();

$ast->query("Property[key='something']");
```

**Comment by mck89** [comment]
No, not in that way, but since the selector is a string you can just use something like `Property[$prop]` where $prop is a variable that contains the key you are looking for and it will give all the nodes that have that key, than you can just access nodes properties.

**Comment by mck89** [comment]
Ok now i understand.
You should json_encode the ast to understand how to make a selector, in this case for example you have a `Property` node with an attribute `key` that contains the indentifier whose `name` is `foo`, so you can use:
```php
$props = $ast->query("Property[key.name='foo']");
```
And then you can get for example the value of the first matched property that have been found:
```php
echo $props->get(0)->getValue()->getValue(); // bar
```

**Comment by heidkaemper** [comment]
Ahh perfect, that's exactly what I needed.
Thank you so much!
