### ISSUE TITLE
Generating optimized autoload files error → Could not scan for classes inside

### ISSUE THREAD

**Issue by remcotolsma** [mck89/peast#59]
After running `composer install --no-dev --prefer-dist --optimize-autoloader` we noticed the following error:

```
Generating optimized autoload files

  In ClassMapGenerator.php line 73:

    Could not scan for classes inside "vendor/mck89/peast/test/Peast" which does not appear to be a file nor a folder
```

Is this related to the following:

https://github.com/mck89/peast/blob/bd4c30d2988cfc6fcd09e48157b69c6bd0e36071/composer.json#L18-L23

https://github.com/mck89/peast/blob/bd4c30d2988cfc6fcd09e48157b69c6bd0e36071/.gitattributes#L5

The `test` folder is part of `export-ignore` but is registered in the `composer.json` `autoload` property.

Should it be moved the `autoload-dev` property?

```json
    "autoload": {
        "psr-4": {
            "Peast\\": "lib/Peast/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Peast\\test\\": "test/Peast/"
        }
    },
```

https://getcomposer.org/doc/04-schema.md#autoload-dev

**Comment by mck89** [comment]
Yes, I think you're right, i'll make some tests to check different cases with the fix you proposed.

**Comment by mck89** [comment]
I've applied the fix you proposed and it seems to work. I couldn't reproduce the error you mentioned but i think it depends on the composer version, so let me know if the error is still present. Thank you!
