### ISSUE TITLE
Improper regex string replacement (for a lack of better words)

### ISSUE THREAD

**Issue by dehlirious** [mck89/peast#66]
Code to duplicate the problem: (php8.3)
```
$jsCode = <<<'EOF'
function test() {
	var noop = function () {},
		localIPs = {},
		ipRegex = /([0-9]{1,3}(\.[0-9]{1,3}){3}|[a-f0-9]{1,4}(:[a-f0-9]{1,4}){7})/g,
		ipv6 = /^(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$|^(?:(?=(?:.?(?::|::))(?:[0-9a-fA-F]{0,4}(?::|$))){0,8}(?:(?:[0-9a-fA-F]{0,4}:){1,7}|:))([0-9a-fA-F]{0,4}:(?:.?(?::|(?!(?:.?[0-9a-fA-F]:){1,7}(?:.)?$)))?)?$/;
}
EOF;

$peast = \Peast\Peast::latest($jsCode);
$ast = $peast->parse();

$traverser = new \Peast\Traverser();
$traverser->addFunction(function ($node)  {
	if ($node instanceof \Peast\Syntax\Node\Literal && is_string($node->getValue())) {
		$str = $node->getRaw();
		if (strpos($str, '`') !== false || strpos($str, '/') === 0) {
			//return;
		}
		
		$stringContent = $node->getValue();

		$replacement = "Test";
		
		//$node->setValue("" . $replacement . ""); // Set the raw value to include quotes
		$node->setRaw("'" . $replacement . "'"); // Set the raw value to include quotes
	}
});
$traverser->traverse($ast);

$renderer = new \Peast\Renderer();
$renderer->setFormatter(new \Peast\Formatter\PrettyPrint);
$modifiedSource = $renderer->render($ast);

echo $modifiedSource;
```

output:
```
function test () {
	var noop = function () {
		},
		localIPs = {},
		ipRegex = //Test',
		ipv6 = //Test';
}
```

Instead of changing the regex to 'Test' , it changes it to `ipRegex = //Test',`
(the first character is always removed it seems - with no errors) -- and '//' shouldn't exist

`$node->getValue()` returns the valid string content, but setRaw/setValue improperly replaces string content. (leaving the first and last / , and removing the first character. Via setValue, output is `= //est';`

Temporary solution:
```
if (strpos($str, '`') !== false || strpos($str, '/') === 0) {
	return;
}
```
after `$str = $node->getRaw();`

Also to note: the exceptions in `function setRaw($raw)` are completely unnecessary(in my eyes), If I want to turn 'string' into calltofunctionorarray('arrayindexorparametertopass'), i should be allowed to! why do You need to care if I'm setting an invalid string? What's the purpose of setRaw if it's the same as setValue?(ofc setting the quotation type is the difference) I would expect set raw to allow raw setting , not explicitly mandating a string - a explanation as to why this is would be nice.

**Comment by mck89** [comment]
The `value` property is defined by the ESTree specification on all literals, but while for all the other literals it makes sense, for regexps it's not that clear what it should contain since regexps have 2 informations, the pattern and the modifiers, so which one is the value?

For this reason i chose to make `setValue` and `setRaw` exactly the same for regexps and `setRaw` must be called in the form you see in the code, so for regexps:

```
$node->setRaw("/Test/");
//or
$node->setValue("/Test/");
```

That is also the reason why you get that strange behaviour that renders `//Test` since it uses "Test" as regexp modifiers instead of patterns since delimiters are missing. Maybe it's not very useful but i don't want to introduce a breaking change for this right now.

If you want to set only the pattern you can use `$node->setPattern("Test");` and you will get exactly what you expect.

For the second part of the issue i don't agree with you, it does not make sense for me to allow a string that is not a string.
If you need to replace something wih a function call you can for example do this:

```
$traverser->addFunction(function ($node)  {
	if ($node instanceof \Peast\Syntax\Node\Literal && is_string($node->getValue())) {
		$str = $node->getRaw();
		if (strpos($str, '`') !== false || strpos($str, '/') === 0) {
			//return;
		}

        return [
            \Peast\Peast::latest('call("test")')->parse()->getBody()[0]->getExpression(),
            Peast\Traverser::DONT_TRAVERSE_CHILD_NODES
        ];
	}
});
```

And you will get:
```
function test () {
        var noop = function () {
                },
                localIPs = {},
                ipRegex = call("test"),
                ipv6 = call("test");
}
```

**Comment by dehlirious** [comment]
> The `value` property is defined by the ESTree specification on all literals, but while for all the other literals it makes sense, for regexps it's not that clear what it should contain since regexps have 2 informations, the pattern and the modifiers, so which one is the value?
> 
> For this reason i chose to make `setValue` and `setRaw` exactly the same for regexps and `setRaw` must be called in the form you see in the code, so for regexps:
> 
> ```
> $node->setRaw("/Test/");
> //or
> $node->setValue("/Test/");
> ```
> 
> That is also the reason why you get that strange behaviour that renders `//Test` since it uses "Test" as regexp modifiers instead of patterns since delimiters are missing. Maybe it's not very useful but i don't want to introduce a breaking change for this right now.
> 
> If you want to set only the pattern you can use `$node->setPattern("Test");` and you will get exactly what you expect.
> 
> For the second part of the issue i don't agree with you, it does not make sense for me to allow a string that is not a string.
> If you need to replace something wih a function call you can for example do this:
> 
> ```
> $traverser->addFunction(function ($node)  {
> 	if ($node instanceof \Peast\Syntax\Node\Literal && is_string($node->getValue())) {
> 		$str = $node->getRaw();
> 		if (strpos($str, '`') !== false || strpos($str, '/') === 0) {
> 			//return;
> 		}
> 
>         return [
>             \Peast\Peast::latest('call("test")')->parse()->getBody()[0]->getExpression(),
>             Peast\Traverser::DONT_TRAVERSE_CHILD_NODES
>         ];
> 	}
> });
> ```
> 
> And you will get:
> ```
> function test () {
>         var noop = function () {
>                 },
>                 localIPs = {},
>                 ipRegex = call("test"),
>                 ipv6 = call("test");
> }
> ```
> 

Wonderful break down!
Understood.  With what I was trying to do, I'm thinking I just was not being specific enough, trying to process all literals instead of just what I wanted which was specifically strings, not regexp patterns. Trying to process some strings while having a rexgexp existent, and having the output I had, is what lead me to believe there was an issue. To be honest I was not aware it worked like that, that is useful information.

And as for your implementation of replacing something with a function call, that makes sense. A bit better than what I was trying. 

Seems overall my issues seemed to be more from a lack of understanding rather than anything else. Thanks for your time.
