### ISSUE TITLE
In compact, you can remove () of new object

### ISSUE THREAD

**Issue by tristanleboss** [mck89/peast#9]
By comparing the minified JS of jQuery and the output of PEAST, I noticed PEAST add emptyy parenthesis for `new` operator.

For example, in original jQuery minified file, you have: 
```
return +new Date
```
WIth PEAST, it becomes:
```
return +new Date();
```

It seems these parenthesis are not needed when no arguments are passed to the constructor.

**Comment by mck89** [comment]
It's true in the case you mentioned, but for example in this code:
```
new test()();
```
both parenthesis groups are necessary even if no arguments are supplied to the constructor.

Right now i prefer to not introduce more logic in the Renderer to keep it clean and faster, i think this kind of micro-optimizations are better suited for a code compressor.

Thank you anyway for reporting.
